### PR TITLE
Create walking skeleton

### LINKED ISSUE #83: Create 'walking skeleton' for planned features

### PR DESCRIPTION
**Pull request by qwoprocks**
Fixes #83

### CODE REVIEW

**Review by raysonkoh — COMMENTED** [review]
Looks fine to me.

**Review by tankangliang — COMMENTED** [review]
LGTM

**Review by LeeEnHao — APPROVED** [review]
Looks good

**Comment by rtshkmr** [comment]
LGTM! TagFactory looks good too 👍

**Pull request merged**
