### PR TITLE
Create new workflow that automatically generates and commits UML pngs

### PR DESCRIPTION
**Pull request by qwoprocks**
Workflow is only triggered when changes are made to the .puml files in the `docs/diagrams` directory.

Tested on my own branch, works well.

### CODE REVIEW

**Review by tankangliang — APPROVED** [review]
LGTM

**Review by LeeEnHao — APPROVED** [review]
Let's try it

**Review by raysonkoh — COMMENTED** [review]
LGTM

**Review by rtshkmr — APPROVED** [review]
LGTM 👍

**Pull request merged**
